version: 2

jobs:
  buildImage:
    docker:
      - image: web3f/ci-commons:v2.4.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.7
      - run:
          command: |
            /scripts/build-image.sh web3f/mongo-express .

  helmLint:
    docker:
      - image: web3f/ci-commons:v2.4.6
    steps:
      - checkout
      - run:
          command: |
            helm lint ./charts/mongo-express

  integrationTests:
    docker:
      - image: web3f/ci-commons:v2.4.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v2.4.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          command: |
            /scripts/publish-image.sh web3f/mongo-express

  publishChart:
    docker:
      - image: web3f/ci-commons:v2.4.6
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - helmLint:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
          requires:
            - helmLint    
      - integrationTests:
          filters:
            tags:
              only: /.*/
          requires:
            - buildImage
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - integrationTests
