apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    {{ if .Values.certificate.enabled }}
    cert-manager.io/cluster-issuer: "letsencrypt"
    {{ end }}
    {{ if .Values.ingress.whitelist-source-ips }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.whitelist-source-ips }}"
    {{ end }}
spec:
  {{ if .Values.certificate.enabled }}
  tls:
  - hosts:
      - {{ include "mongo-express.backend-domain" . }}
    secretName: {{ include "mongo-express.tls-secret-name" . }}
  {{ end }}  
  rules:
  - host: {{ include "mongo-express.backend-domain" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: {{ .Values.backendPort }}
