environments:
  ci:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: mongodb-replicaset
    chart: bitnami/mongodb
    version: 10.30.9
    values:
      - ./config/mongodb.yaml.gotmpl
